// This file is auto-generated. Do not edit manually.
// Run 'npm run auto-import-components' to update.

import {Repos} from '../../../types/common';
import {createComponentConfig} from '../utils';
import {Component} from '../types';

export const autoGeneratedComponents: Component[] = ([
    "AvatarStack",
    "ClipboardIcon",
    "ControlLabel",
    "CopyToClipboard",
    "TableColumnSetup",
    "TreeList",
    "TreeSelect",
] as string[]).map((name) =>
    createComponentConfig(name, Repos.Uikit),
);
